export const RESPONSE_CODE = {
  INPUT_DATA_ERROR: 'INPUT_DATA_ERROR',
  FATAL_INPUT_ERROR: 'FATAL INPUTERROR',
  USER_REGISTRATION_SUCCESSFUL: 'USER_REGISTRATION_SUCCESSFUL',
  USER_REGISTRATION_FAILED: 'USER_REGISTRATION_FAILED'
} as const
