export const RESPONSE_CODE = {
  INPUT_DATA_ERROR: 'INPUT_DATA_ERROR',
  FATAL_INPUT_ERROR: 'FATAL INPUTERROR',
  USER_REGISTRATION_SUCCESSFUL: 'USER_REGISTRATION_SUCCESSFUL',
  USER_REGISTRATION_FAILED: 'USER_REGISTRATION_FAILED',
  USER_LOGIN_SUCCESSFUL: 'USER_LOGIN_SUCCESSFUL',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  FATAL_AUTHENTICATION_FAILURE: 'FATAL_AUTHENTICATION_FAILURE',
  USER_LOGOUT_SUCCESSFUL: 'USER_LOGOUT_SUCCESSFUL',
  USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED'
} as const
